title: Bonsai Conference 2024
logo: /assets/images/bonsai.svg
email: conference@bonsai-rx.org
description: |
  December 2 to 6, 2024
  Sainsbury Wellcome Centre
  London, UK
baseurl: "/2024"
url: https://conference.bonsai.dev
github_username:  bonsai-rx
mastodon:
  - username: bonsai
    instance: neuromatch.social

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - "**README.md"

header_pages:
  - about.md
  - _pages/program.md
  - _pages/accommodation.md
  - _pages/registration.md
