# Builds and publishes the conference to gh-pages branch
name: Build website

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:
permissions:
  # Both required by actions/deploy-pages
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./2024"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./2024"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}